'''
Goal of LSTM microservice:
1. LSTM microservice will accept the GitHub data from Flask microservice and will forecast the data for next 1 year based on past 30 days
2. It will also plot three different graph (i.e.  "Model Loss", "LSTM Generated Data", "All Issues Data") using matplot lib 
3. This graph will be stored as image in Google Cloud Storage.
4. The image URL are then returned back to Flask microservice.
'''
# Import all the required packages
from flask import Flask, jsonify, request, make_response
import os
from dateutil import *
from datetime import timedelta
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import time
from flask_cors import CORS
from datetime import datetime
import github3
import json

# Tensorflow (Keras & LSTM) related packages
import tensorflow as tf
from tensorflow.python.keras import Sequential
#from tensorflow.python.keras.layers import Input, Dense, LSTM, Dropout
from tensorflow.keras.layers import Input, Dense, LSTM, Dropout
from tensorflow.python.keras.callbacks import EarlyStopping
from sklearn.preprocessing import MinMaxScaler
from pandas import DataFrame, Series

# Import required storage package from Google Cloud Storage
from google.cloud import storage

# Initilize flask app
app = Flask(__name__)
# Handles CORS (cross-origin resource sharing)
CORS(app)
# Initlize Google cloud storage client
client = storage.Client()

# Add response headers to accept all types of  requests

def build_preflight_response():
    response = make_response()
    response.headers.add("Access-Control-Allow-Origin", "*")
    response.headers.add("Access-Control-Allow-Headers", "Content-Type")
    response.headers.add("Access-Control-Allow-Methods",
                         "PUT, GET, POST, DELETE, OPTIONS")
    return response

#  Modify response headers when returning to the origin

def build_actual_response(response):
    response.headers.set("Access-Control-Allow-Origin", "*")
    response.headers.set("Access-Control-Allow-Methods",
                         "PUT, GET, POST, DELETE, OPTIONS")
    return response



gitHeaders = {
    "Authorization": f"token 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",
    "Accept": "application/vnd.github.v3+json",
}

BASE_IMAGE_PATH = os.environ.get(
        'BASE_IMAGE_PATH', '/Users/anushasp/Desktop/HW5_Sonte_Parameshwar,Anusha/src/Forecasting/TensorFlow_LSTM/')
    # DO NOT DELETE "static/images" FOLDER as it is used to store figures/images generated by matplotlib
LOCAL_IMAGE_PATH = "static/images/"
LOCAL_REPO_PATH = "static/repofiles/"

'''
API route path is  "/api/forecast"
This API will accept only POST request
'''

@app.route('/api/forecast/lstm', methods=['POST'])
def forecast():
    body = request.get_json()
    issues = body["issues"]
    type = body["type"]
    repo_name = body["repo"]
    data_frame = pd.DataFrame(issues)
    df1 = data_frame.groupby([type], as_index=False).count()
    df = df1[[type, 'issue_number']]
    df.columns = ['ds', 'y']
    df['ds'] = df['ds'].astype('datetime64[ns]')
    array = df.to_numpy()
    x = np.array([time.mktime(i[0].timetuple()) for i in array])
    y = np.array([i[1] for i in array])

    lzip = lambda *x: list(zip(*x))

    days = df.groupby('ds')['ds'].value_counts()
    Y = df['y'].values
    X = lzip(*days.index.values)[0]
    firstDay = min(X)

    '''
    To achieve data consistancy with both actual data and predicted values, 
    add zeros to dates that do not have orders
    [firstDay + timedelta(days=day) for day in range((max(X) - firstDay).days + 1)]
    '''
    Ys = [0, ]*((max(X) - firstDay).days + 1)
    days = pd.Series([firstDay + timedelta(days=i)
                      for i in range(len(Ys))])
    for x, y in zip(X, Y):
        Ys[(x - firstDay).days] = y

    # Modify the data that is suitable for LSTM
    Ys = np.array(Ys)
    Ys = Ys.astype('float32')
    Ys = np.reshape(Ys, (-1, 1))
    # Apply min max scaler to transform the data
    scaler = MinMaxScaler(feature_range=(0, 1))
    Ys = scaler.fit_transform(Ys)
    # Divide training - test data with 80-20 split
    train_size = int(len(Ys) * 0.80)
    test_size = len(Ys) - train_size
    train, test = Ys[0:train_size, :], Ys[train_size:len(Ys), :]
    print('train size:', len(train), ", test size:", len(test))

    # Create the training and test dataset
    def create_dataset(dataset, look_back=1):
        X, Y = [], []
        for i in range(len(dataset)-look_back-1):
            a = dataset[i:(i+look_back), 0]
            X.append(a)
            Y.append(dataset[i + look_back, 0])
        return np.array(X), np.array(Y)
    '''
    Look back decides how many days of data the model looks at for prediction
    Here LSTM looks at approximately one month data
    '''
    look_back = 10
    X_train, Y_train = create_dataset(train, look_back)
    X_test, Y_test = create_dataset(test, look_back)

    # Reshape input to be [samples, time steps, features]
    X_train = np.reshape(X_train, (X_train.shape[0], 1, X_train.shape[1]))
    print("X_test shape before reshaping:", X_test.shape)
    X_test = np.reshape(X_test, (X_test.shape[0], 1, X_test.shape[1]))
    print("X_test shape after reshaping:", X_test.shape)


    # Verifying the shapes
    X_train.shape, X_test.shape, Y_train.shape, Y_test.shape

    # Model to forecast
    model = Sequential()
    model.add(LSTM(100, input_shape=(X_train.shape[1], X_train.shape[2])))
    model.add(Dropout(0.2))
    model.add(Dense(1))
    model.compile(loss='mean_squared_error', optimizer='adam')

    # Fit the model with training data and set appropriate hyper parameters
    history = model.fit(X_train, Y_train, epochs=20, batch_size=70, validation_data=(X_test, Y_test),
                        callbacks=[EarlyStopping(monitor='val_loss', patience=10)], verbose=1, shuffle=False)

    '''
    Creating image URL
    BASE_IMAGE_PATH refers to Google Cloud Storage Bucket URL.Add your Base Image Path in line 145
    if you want to run the application local
    LOCAL_IMAGE_PATH refers local directory where the figures generated by matplotlib are stored
    These locally stored images will then be uploaded to Google Cloud Storage
    '''
    BASE_IMAGE_PATH = os.environ.get(
        'BASE_IMAGE_PATH', 'Your_Base_Image_path')
    # DO NOT DELETE "static/images" FOLDER as it is used to store figures/images generated by matplotlib
    LOCAL_IMAGE_PATH = "static/images/"

    # Creating the image path for model loss, LSTM generated image and all issues data image
    MODEL_LOSS_IMAGE_NAME = "model_loss_" + type +"_"+ repo_name + ".png"
    MODEL_LOSS_URL = BASE_IMAGE_PATH + MODEL_LOSS_IMAGE_NAME

    COMMITS_GENERATED_IMAGE_NAME = "commits_generated_data_" + type +"_" + repo_name + ".png"
    COMMITS_GENERATED_URL = BASE_IMAGE_PATH + COMMITS_GENERATED_IMAGE_NAME

    ALL_ISSUES_DATA_IMAGE = "all_issues_data_" + type + "_"+ repo_name + ".png"
    ALL_ISSUES_DATA_URL = BASE_IMAGE_PATH + ALL_ISSUES_DATA_IMAGE

    PULLL_ISSUES_DATA_IMAGE_NAME = "pull_data_" + type + "_"+ repo_name + ".png"
    PULL_ISSUES_DATA_URL = BASE_IMAGE_PATH + PULLL_ISSUES_DATA_IMAGE_NAME

    BRANCHES_GENERATED_IMAGE_NAME = "Branches_data_" + type + "_"+ repo_name + ".png"
    BRANCHES_GENERATED_URL = BASE_IMAGE_PATH + BRANCHES_GENERATED_IMAGE_NAME

    CONTRIBUTORS_GENERATED_IMAGE_NAME = "Contribuots_data_" + type + "_"+ repo_name + ".png"
    CONTRIBUTORS_GENERATED_URL = BASE_IMAGE_PATH + CONTRIBUTORS_GENERATED_IMAGE_NAME

    RELEASES_GENERATED_IMAGE_NAME = "Releases_data_" + type + "_"+ repo_name + ".png"
    RELEASES_GENERATED_URL = BASE_IMAGE_PATH + RELEASES_GENERATED_IMAGE_NAME

    # Add your unique Bucket Name if you want to run it local
    BUCKET_NAME = os.environ.get(
        'BUCKET_NAME', 'Your_BUCKET_NAME')

    # Model summary()

    # Plot the model loss image
    plt.figure(figsize=(8, 4))
    plt.plot(history.history['loss'], label='Train Loss')
    plt.plot(history.history['val_loss'], label='Test Loss')
    plt.title('Model Loss For ' + type)
    plt.ylabel('Loss')
    plt.xlabel('Epochs')
    plt.legend(loc='upper right')
    # Save the figure in /static/images folder
    plt.savefig(LOCAL_IMAGE_PATH + MODEL_LOSS_IMAGE_NAME)

    # Predict issues for test data
    y_pred = model.predict(X_test)

    # Plot the LSTM Generated image
    fig, axs = plt.subplots(1, 1, figsize=(10, 4))
    X = mdates.date2num(days)
    axs.plot(np.arange(0, len(Y_train)), Y_train, 'g', label="history")
    axs.plot(np.arange(len(Y_train), len(Y_train) + len(Y_test)),
             Y_test, marker='.', label="true")
    axs.plot(np.arange(len(Y_train), len(Y_train) + len(Y_test)),
             y_pred, 'r', label="prediction")
    axs.legend()
    axs.set_title('Commits forecast Generated Data')
    axs.set_xlabel('Time Steps')
    axs.set_ylabel('Commits')
    # Save the figure in /static/images folder
    plt.savefig(LOCAL_IMAGE_PATH + COMMITS_GENERATED_IMAGE_NAME)

    # Plot the LSTM Generated image
    fig, axs = plt.subplots(1, 1, figsize=(10, 4))
    X = mdates.date2num(days)
    axs.plot(np.arange(0, len(Y_train)), Y_train, 'g', label="history")
    axs.plot(np.arange(len(Y_train), len(Y_train) + len(Y_test)),
             Y_test, marker='.', label="true")
    axs.plot(np.arange(len(Y_train), len(Y_train) + len(Y_test)),
             y_pred, 'r', label="prediction")
    axs.legend()
    axs.set_title('Contributors forecast Generated Data')
    axs.set_xlabel('Time Steps')
    axs.set_ylabel('Contributors')
    # Save the figure in /static/images folder
    plt.savefig(LOCAL_IMAGE_PATH + CONTRIBUTORS_GENERATED_IMAGE_NAME)


    #Branches image
    fig, axs = plt.subplots(1, 1, figsize=(12, 6))  
    X = mdates.date2num(days)
    axs.plot(np.arange(0, len(Y_train)), Y_train, 'b', linestyle='-', label="history")  
    axs.plot(np.arange(len(Y_train), len(Y_train) + len(Y_test)),
    Y_test, marker='.', linestyle='-', color='orange', label="true")  
    axs.plot(np.arange(len(Y_train), len(Y_train) + len(Y_test)),
    y_pred, 'm', linestyle='--', label="prediction") 
    axs.legend(loc='upper right')  
    axs.set_title('Branches forecast Generated Data') 
    axs.set_xlabel('Time Steps')  
    axs.set_ylabel('Branches')  
    plt.savefig(LOCAL_IMAGE_PATH + BRANCHES_GENERATED_IMAGE_NAME)
    plt.show()

    #Contributors image
    fig, axs = plt.subplots(1, 1, figsize=(12, 6))  
    X = mdates.date2num(days)
    axs.plot(np.arange(0, len(Y_train)), Y_train, 'b', linestyle='-', label="history")  
    axs.plot(np.arange(len(Y_train), len(Y_train) + len(Y_test)),
    Y_test, marker='.', linestyle='-', color='orange', label="true")  
    axs.plot(np.arange(len(Y_train), len(Y_train) + len(Y_test)),
    y_pred, 'm', linestyle='--', label="prediction") 
    axs.legend(loc='upper right')  
    axs.set_title('Branches forecast Generated Data') 
    axs.set_xlabel('Time Steps')  
    axs.set_ylabel('Branches')  
    plt.savefig(LOCAL_IMAGE_PATH + BRANCHES_GENERATED_IMAGE_NAME)
    plt.show()

    # Plot the All Issues data images
    fig, axs = plt.subplots(1, 1, figsize=(10, 4))
    X = mdates.date2num(days)
    axs.plot(X, Ys, 'purple', marker='.')
    locator = mdates.AutoDateLocator()
    axs.xaxis.set_major_locator(locator)
    axs.xaxis.set_major_formatter(mdates.AutoDateFormatter(locator))
    axs.legend()
    axs.set_title('All Issues Data')
    axs.set_xlabel('Date')
    axs.set_ylabel('Issues')
    # Save the figure in /static/images folder
    plt.savefig(LOCAL_IMAGE_PATH + ALL_ISSUES_DATA_IMAGE)

    # Uploads an images into the google cloud storage bucket
    bucket = client.get_bucket(BUCKET_NAME)
    new_blob = bucket.blob(MODEL_LOSS_IMAGE_NAME)
    new_blob.upload_from_filename(
        filename=LOCAL_IMAGE_PATH + MODEL_LOSS_IMAGE_NAME)
    new_blob = bucket.blob(ALL_ISSUES_DATA_IMAGE)
    new_blob.upload_from_filename(
        filename=LOCAL_IMAGE_PATH + ALL_ISSUES_DATA_IMAGE)
    new_blob = bucket.blob(COMMITS_GENERATED_IMAGE_NAME)
    new_blob.upload_from_filename(
        filename=LOCAL_IMAGE_PATH + COMMITS_GENERATED_IMAGE_NAME)
    
    repo_name = body["repo_name"]
    repo_key = body["repo_key"]
    start_date = body["start_date"]
    end_date = body["end_date"]

     # Call the method
    file_name = get_pulls_data(repo_name, repo_key, start_date, end_date)  

    issues = [json.loads(line) for line in open(file_name)]
    df_new = DataFrame(issues)

    REPO_FILENAME=  BASE_IMAGE_PATH + LOCAL_IMAGE_PATH + repo_name + '.csv'

    #Creating csv file
    df_new.to_csv(REPO_FILENAME, sep=',', encoding='utf-8', index=False)

    dateOfWeekMaxCreated = maxIssuesCreatedDate(REPO_FILENAME)
    dateOfWeekMaxClosed = maxIssuesClosedDate(REPO_FILENAME)
    
    dayOfWeekMaxCreated, monthOfYearMaxCreated = convertedDate(dateOfWeekMaxCreated)
    dayOfWeekMaxClosed, monthOfYearMaxClosed = convertedDate(dateOfWeekMaxClosed)


    # Construct the response
    json_response = {
        "all_issues_data_image": ALL_ISSUES_DATA_URL,
        "pullsForecast" : PULL_ISSUES_DATA_URL,
        "commitsForecast" : COMMITS_GENERATED_URL,
        "branchesForecast" : BRANCHES_GENERATED_URL,
        "contributersForecast": CONTRIBUTORS_GENERATED_URL,
        "ReleasesForecat": RELEASES_GENERATED_URL,
        "dayOfWeekMaxCreated": dayOfWeekMaxCreated,
        "dayOfWeekMaxClosed": dayOfWeekMaxClosed,
        "monthOfYearMaxClosed": monthOfYearMaxClosed
    }
    # Returns image url back to flask microservice
    return jsonify(json_response)

def get_pulls_data(repo_name,repo_key, start_date, end_date):

    gitToken = os.environ.get(
        'GITHUB_TOKEN', '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')

    gh = github3.login(token=gitToken) 

    REPO_FILENAME=  BASE_IMAGE_PATH + LOCAL_REPO_PATH + repo_name + '.json'

    f = open(REPO_FILENAME, 'w')
    # Issues
    pr_query = f'type:pr repo:{repo_key} created:{start_date}..{end_date}'
    for issue in gh.search_issues(pr_query):
            pr_data = {}
            current_pr = issue.as_json()
            current_pr = json.loads(current_pr)
            pr_data['type'] = 'pull_request'
            pr_data['pr_number'] = current_pr["number"]
            pr_data['created_at'] = current_pr["created_at"][0:10]
            if current_pr["closed_at"] is None:
                pr_data['closed_at'] = current_pr["closed_at"]
            else:
                pr_data['closed_at'] = current_pr["closed_at"][0:10]
            pr_data['state'] = current_pr["state"]
            pr_data['author'] = current_pr["user"]["login"]
            out = json.dumps(pr_data)
            f.write(out + '\n')
    f.close()
    return REPO_FILENAME

def maxIssuesCreatedDate(file):
    df = pd.read_csv(file)
    df1 = df.groupby(['created_at']).count().reset_index()
    maxIssuesCreateddDate = df1.sort_values('issue_number', ascending=False).head(1).iloc[0]['created_at']
    return maxIssuesCreateddDate

def maxIssuesClosedDate(file):
    df = pd.read_csv(file)
    df1 = df.groupby(['closed_at']).count().reset_index()
    maxIssuesClosedDate = df1.sort_values('issue_number', ascending=False).head(1).iloc[0]['closed_at']
    return maxIssuesClosedDate

def convertedDate(data):
    year, month, day = (int(x) for x in data.split('-'))
    formattedDateTime = datetime.date(year, month, day)
    formattedDay = formattedDateTime.strftime("%A")
    formattedMonth = formattedDateTime.strftime("%B")
    return formattedDay, formattedMonth


# Run LSTM app server on port 8080
if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0', port=8080)
